#!/usr/local/bin/node
"use strict";

const fs = require('fs');
const readline = require('readline');

const match = require('./matcher');

const util = {
  add: (point1, point2) => [point1[0] + point2[0], point1[1] + point2[1]],
  subtract: (point1, point2) => [point1[0] - point2[0], point1[1] - point2[1]],
};

const mapToSquare = (median) => {
  return median.map((x) => [x[0], 900 - x[1]]);
}

const encode = (matcher, row) => {
  const result = [];
  // TODO(skishore): Figure out how to properly decode UTF-8 or -16 in
  // Javascript and then use one of those encodings here instead of this hack.
  const codepoint = row.character.charCodeAt(0);
  result.push(codepoint & 0xff);
  result.push(codepoint >> 8);
  // Push the medians into the binary representation.
  const medians = row.medians.map(mapToSquare);
  const preprocessed = matcher.preprocess(medians);
  result.push(preprocessed.length);
  preprocessed.map((median) => {
    result.push(median.length);
    median.map((point) => {
      result.push(point[0]);
      result.push(point[1]);
    });
  });
  result.map((x) => { if (!(0 <= x && x < 256)) throw preprocessed; });
  return new Buffer(result);
}

const main = () => {
  const input = fs.createReadStream('makemeahanzi.txt');
  const reader = readline.createInterface({input: input});
  const writer = fs.createWriteStream('medians.bin');
  const matcher = new match.Matcher([]);
  reader.on('line', (line) => {
    const row = JSON.parse(line.trim());
    writer.write(encode(matcher, row));
  });
  reader.on('end', () => writer.end());
}

main();
